baseurl = "http://www.francocurotto.com"
title = "francocurotto"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"

#paginate = 20
#pygmentsStyle = "bw"
#pygmentsCodeFences = true
#pygmentsCodeFencesGuessSyntax = true
#enableEmoji = true

[params]
author = "Franco Curotto"
description = "Franco's Site"
info = ["Electical Engineer", "Digital Electronic Specialist"]
avatarURL = "images/avatar-20210806.jpg"
dateFormat = "January 2, 2006"
colorScheme = "auto"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/francocurotto/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/francocurotto/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "CV"
weight = 1
url = "cv/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Blog"
weight = 3
url = "blog/"

[[languages.en.menu.main]]
name = "Contact"
weight = 5
url = "contact/"

[languages.es]
languageName = ":es:"

[languages.es.params]
author = "Franco Curotto"
info = ["Ingeniero Eléctrico", "Especialista en Electrónica Digital"]

[[languages.es.menu.main]]
name = "CV"
weight = 1
url = "cv/"

[[languages.es.menu.main]]
name = "Proyectos"
weight = 2
url = "projects/"

[[languages.es.menu.main]]
name = "Blog"
weight = 3
url = "blog/"

[[languages.es.menu.main]]
name = "Contacto"
weight = 5
url = "contact/"
