baseurl = "http://www.francocurotto.com"
title = "FrancoCurotto"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"

[params]
author = "Franco Curotto"
description = "Franco's Site"
info = ["Electical Engineer", "Digital Electronic Specialist", "ğŸ˜Emoji ExpertğŸ”¥"]
avatarURL = "images/avatar-20210806.jpg"
dateFormat = "January 2, 2006"
since = 2022
colorScheme = "auto"
favicon_16 = "images/favicon-16x16.png"
favicon_32 = "images/favicon-32x32.png"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-at"
weight = 1
url = "mailto:francocurotto@gmail.com"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/francocurotto/"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 3
url = "https://github.com/francocurotto/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "ğŸ“ƒCV"
weight = 1
url = "cv/"

[[languages.en.menu.main]]
name = "ğŸ› ï¸Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "ğŸ“¢Blog"
weight = 3
url = "blog/"

[[languages.en.menu.main]]
name = "ğŸ“§Contact"
weight = 4
url = "contact/"

[languages.es]
languageName = ":es:"

[languages.es.params]
author = "Franco Curotto"
info = ["Ingeniero ElÃ©ctrico", "Especialista en ElectrÃ³nica Digital", "ğŸ˜Experto en EmojisğŸ”¥"]

[[languages.es.menu.main]]
name = "ğŸ“ƒCV"
weight = 1
url = "cv/"

[[languages.es.menu.main]]
name = "ğŸ› ï¸Proyectos"
weight = 2
url = "projects/"

[[languages.es.menu.main]]
name = "ğŸ“¢Blog"
weight = 3
url = "blog/"

[[languages.es.menu.main]]
name = "ğŸ“§Contacto"
weight = 4
url = "contact/"
